FROM ubuntu:cosmic
MAINTAINER Robin Marx <robin.marx@uhasselt.be>

# sudo docker build -t qvis/server:latest qvis/
# sudo docker run --privileged --name qvis_server -d qvis/server:latest
# sudo docker exec -it qvis_server bash

		
# install necessary packages
RUN 						\
	apt-get update 			\
	&& apt-get upgrade -y 	\
	&& apt-get install -y git-core curl nano libssl-dev python3-dev python3-pip iproute2

RUN git clone https://github.com/rmarx/aioquic.git /srv/aioquic
RUN cd /srv/aioquic \
  # && git reset 351da27bfbc705274abb6f315754c10005375b44 --hard \
  && pip3 install -e . \
  && pip3 install aiofiles asgiref httpbin starlette wsproto \
  && mkdir /srv/aioquic/qlog/

ENTRYPOINT ["bash"]
